In [2]:
import pandas as pd

In [ ]:
student={
    "rollno":[101,102,103,104,None],
    "name":['raj','ravi','riya','hardik','tanvi'],
    "age":[20,22,21,None,22],
    'gender':['male','male','male','male','female'],
    "city":['indore','satna','katni',None,'maihar']
    
}

In [8]:
df=pd.DataFrame(student)
df

   rollno    name   age  gender    city
0   101.0     raj  20.0    male  indore
1   102.0    ravi  22.0    male   satna
2   103.0    riya  21.0    male   katni
3   104.0  hardik   NaN    male    None
4     NaN   tanvi  22.0  female  maihar

In [12]:
df.isna()

   rollno   name    age  gender   city
0   False  False  False   False  False
1   False  False  False   False  False
2   False  False  False   False  False
3   False  False   True   False   True
4    True  False  False   False  False

In [13]:
df1=df.dropna()

In [15]:
df1

   rollno  name   age gender    city
0   101.0   raj  20.0   male  indore
1   102.0  ravi  22.0   male   satna
2   103.0  riya  21.0   male   katni

In [16]:
df2=df.fillna("new data")

In [17]:
df2

     rollno    name       age  gender      city
0     101.0     raj      20.0    male    indore
1     102.0    ravi      22.0    male     satna
2     103.0    riya      21.0    male     katni
3     104.0  hardik  new data    male  new data
4  new data   tanvi      22.0  female    maihar

In [18]:
df2=df.fillna(df['age'].mean())

In [19]:
df2

   rollno    name    age  gender    city
0  101.00     raj  20.00    male  indore
1  102.00    ravi  22.00    male   satna
2  103.00    riya  21.00    male   katni
3  104.00  hardik  21.25    male   21.25
4   21.25   tanvi  22.00  female  maihar

In [28]:
df3=df.fillna({'age':df['age'].mean(),'city':df['city'].fillna("jbp")})

In [29]:
df3

   rollno    name    age  gender    city
0   101.0     raj  20.00    male  indore
1   102.0    ravi  22.00    male   satna
2   103.0    riya  21.00    male   katni
3   104.0  hardik  21.25    male     jbp
4     NaN   tanvi  22.00  female  maihar

In [31]:
df=pd.read_csv("Ecommerce_Consumer_Behavior_Analysis_Data.csv")

In [32]:
df.head(0)

Empty DataFrame
Columns: [Customer_ID, Age, Gender, Income_Level, Marital_Status, Education_Level, Occupation, Location, Purchase_Category, Purchase_Amount, Frequency_of_Purchase, Purchase_Channel, Brand_Loyalty, Product_Rating, Time_Spent_on_Product_Research(hours), Social_Media_Influence, Discount_Sensitivity, Return_Rate, Customer_Satisfaction, Engagement_with_Ads, Device_Used_for_Shopping, Payment_Method, Time_of_Purchase, Discount_Used, Customer_Loyalty_Program_Member, Purchase_Intent, Shipping_Preference, Time_to_Decision]
Index: []

[0 rows x 28 columns]

In [33]:
df.dropna()

,Customer_ID,Age,Gender,Income_Level,Marital_Status,Education_Level,Occupation,Location,Purchase_Category,Purchase_Amount,...,Customer_Satisfaction,Engagement_with_Ads,Device_Used_for_Shopping,Payment_Method,Time_of_Purchase,Discount_Used,Customer_Loyalty_Program_Member,Purchase_Intent,Shipping_Preference,Time_to_Decision
1,29-392-9296,49,Male,High,Married,High School,High,Huocheng,Food & Beverages,$222.22,...,5,High,Tablet,PayPal,4/16/2024,True,False,Wants-based,Standard,6
2,84-649-5117,24,Female,Middle,Single,Master's,High,Huzhen,Office Supplies,$426.22,...,7,Low,Smartphone,Debit Card,3/15/2024,True,True,Impulsive,No Preference,3
6,90-144-9193,21,Female,Middle,Divorced,High School,Middle,Liren,Furniture,$486.40,...,9,Low,Desktop,Debit Card,3/15/2024,True,False,Need-based,Express,13
8,37-065-3182,24,Female,High,Divorced,Master's,Middle,Gråbo,Office Supplies,$201.96,...,2,High,Desktop,Cash,6/10/2024,False,False,Need-based,Standard,7
10,44-674-4037,33,Male,Middle,Divorced,Bachelor's,Middle,Punta Gorda,Mobile Accessories,$389.70,...,4,High,Desktop,PayPal,7/2/2024,True,False,Planned,Express,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,08-185-6608,32,Female,High,Divorced,Master's,Middle,Podbrdo,Baby Products,$468.16,...,5,High,Desktop,Credit Card,1/22/2024,False,False,Planned,Standard,2
996,41-366-4205,50,Female,High,Single,High School,Middle,Paquera,Gardening & Outdoors,$69.78,...,6,Low,Tablet,Cash,3/28/2024,True,False,Wants-based,No Preference,9
997,77-241-7621,26,Male,High,Married,Bachelor's,High,Warudoyong,Food & Beverages,$453.37,...,6,High,Desktop,Credit Card,3/11/2024,True,True,Wants-based,Express,9
998,53-091-2176,21,Female,High,Widowed,Bachelor's,Middle,Béziers,Baby Products,$106.15,...,5,Medium,Desktop,Cash,3/30/2024,True,True,Impulsive,Standard,8
999,48-203-9118,21,Female,Middle,Single,High School,High,Dongzhou,Health Care,$378.47,...,10,Low,Tablet,Other,12/8/2024,False,False,Planned,Express,2

In [34]:
df=pd.read_csv("ecommerce_dataset_20cols.csv")

In [35]:
df.head(0)

Empty DataFrame
Columns: [OrderID, CustomerID, CustomerName, Email, Phone, City, State, Country, ProductID, ProductName, Category, Price, Quantity, Discount, PaymentMethod, OrderDate, DeliveryDate, OrderStatus, Rating, ReturnStatus]
Index: []

In [37]:
df.dropna()

,OrderID,CustomerID,CustomerName,Email,Phone,City,State,Country,ProductID,ProductName,Category,Price,Quantity,Discount,PaymentMethod,OrderDate,DeliveryDate,OrderStatus,Rating,ReturnStatus
22,23,1087,Amit,c@gmail.com,1.000000e+10,Mumbai,DL,UK,619,Bag,Accessories,1000.0,3.0,15.0,COD,2023-07-18,2023-07-24,Pending,4.0,Yes
38,39,1448,Amit,c@gmail.com,7.777778e+09,Bhopal,MP,India,625,Watch,Fashion,2000.0,2.0,0.0,UPI,2023-02-12,2023-01-08,Pending,5.0,No
60,61,1510,Raj,c@gmail.com,7.777778e+09,Delhi,DL,India,679,Bag,Accessories,1000.0,2.0,15.0,Card,2023-04-17,2023-02-03,Pending,4.0,No
74,75,1273,Amit,b@gmail.com,7.777778e+09,Delhi,MH,India,567,Shoes,Accessories,4000.0,3.0,10.0,UPI,2023-11-18,2023-08-14,Cancelled,3.0,No
284,285,1032,Amit,a@gmail.com,7.777778e+09,Bhopal,MH,India,681,Bag,Electronics,4000.0,2.0,5.0,Card,2023-03-08,2023-02-21,Pending,3.0,No
288,289,1138,Sara,a@gmail.com,8.888889e+09,Mumbai,DL,USA,614,Watch,Fashion,4000.0,1.0,15.0,UPI,2023-05-23,2023-08-20,Cancelled,5.0,No
353,354,1376,Amit,c@gmail.com,7.777778e+09,Mumbai,MP,UK,510,Bag,Electronics,1000.0,1.0,10.0,Card,2023-01-13,2023-09-15,Cancelled,5.0,No
468,469,1949,Sara,a@gmail.com,8.888889e+09,Indore,DL,India,636,Watch,Accessories,2000.0,2.0,15.0,COD,2023-01-11,2023-07-30,Delivered,3.0,Yes
492,493,1786,Amit,c@gmail.com,7.777778e+09,Mumbai,MH,India,611,Watch,Fashion,4000.0,3.0,5.0,COD,2023-04-12,2023-07-19,Cancelled,2.0,Yes
516,517,1648,Sara,c@gmail.com,8.888889e+09,Bhopal,MP,India,643,Bag,Fashion,4000.0,2.0,15.0,UPI,2023-05-10,2023-08-23,Delivered,4.0,Yes
549,550,1697,Amit,a@gmail.com,1.000000e+10,Indore,MP,UK,595,Watch,Fashion,3000.0,3.0,5.0,Card,2023-04-06,2023-09-23,Cancelled,2.0,No
554,555,1371,John,b@gmail.com,1.000000e+10,Bhopal,MH,UK,565,Phone,Fashion,3000.0,2.0,15.0,COD,2023-02-05,2023-05-17,Pending,5.0,Yes
578,579,1976,Riya,a@gmail.com,1.000000e+10,Mumbai,MH,India,668,Watch,Fashion,1000.0,2.0,5.0,Card,2023-05-28,2023-09-11,Pending,4.0,Yes
585,586,1859,John,c@gmail.com,1.000000e+10,Bhopal,MP,UK,624,Shoes,Accessories,1000.0,1.0,0.0,Card,2023-02-17,2023-03-13,Pending,3.0,Yes
623,624,1417,Riya,a@gmail.com,1.000000e+10,Bhopal,DL,USA,584,Watch,Accessories,3000.0,3.0,10.0,UPI,2023-12-03,2023-06-19,Cancelled,3.0,No
636,637,1637,Raj,a@gmail.com,7.777778e+09,Indore,DL,UK,592,Bag,Accessories,4000.0,2.0,10.0,COD,2023-11-24,2023-01-29,Delivered,3.0,No
721,722,1719,Riya,a@gmail.com,8.888889e+09,Mumbai,MP,UK,576,Laptop,Electronics,3000.0,3.0,5.0,COD,2023-04-18,2023-03-02,Pending,4.0,Yes
789,790,1238,Raj,b@gmail.com,7.777778e+09,Mumbai,DL,USA,581,Watch,Fashion,3000.0,2.0,15.0,UPI,2023-04-02,2023-06-02,Delivered,1.0,Yes
791,792,1171,Amit,b@gmail.com,7.777778e+09,Mumbai,DL,UK,514,Laptop,Electronics,3000.0,3.0,0.0,UPI,2023-03-22,2023-10-15,Cancelled,1.0,No
819,820,1250,Amit,c@gmail.com,8.888889e+09,Bhopal,MH,UK,663,Phone,Electronics,3000.0,4.0,10.0,UPI,2023-05-21,2023-07-19,Pending,4.0,No
883,884,1496,Riya,c@gmail.com,1.000000e+10,Mumbai,DL,USA,650,Watch,Electronics,4000.0,4.0,5.0,UPI,2023-03-11,2023-07-29,Delivered,2.0,Yes
885,886,1929,Raj,c@gmail.com,1.000000e+10,Bhopal,MH,India,547,Shoes,Accessories,4000.0,3.0,15.0,COD,2023-12-27,2023-12-29,Delivered,3.0,Yes
924,925,1285,Sara,b@gmail.com,8.888889e+09,Mumbai,DL,India,669,Laptop,Fashion,2000.0,2.0,15.0,UPI,2023-10-18,2023-07-20,Delivered,5.0,No
936,937,1410,Raj,b@gmail.com,1.000000e+10,Delhi,DL,UK,522,Bag,Accessories,1000.0,1.0,0.0,Card,2023-06-15,2023-04-30,Cancelled,4.0,No
950,951,1612,Amit,a@gmail.com,8.888889e+09,Bhopal,MH,USA,537,Bag,Accessories,4000.0,1.0,0.0,Card,2023-06-12,2023-06-11,Cancelled,5.0,No
964,965,1099,Riya,b@gmail.com,1.000000e+10,Mumbai,DL,USA,509,Laptop,Fashion,2000.0,3.0,10.0,Card,2023-12-12,2023-10-17,Cancelled,3.0,Yes
967,968,1344,Raj,a@gmail.com,1.000000e+10,Delhi,DL,USA,608,Shoes,Fashion,2000.0,3.0,10.0,UPI,2023-09-07,2023-11-01,Cancelled,4.0,No
1019,1020,1006,John,a@gmail.com,1.000000e+10,Bhopal,MH,India,640,Bag,Fashion,4000.0,4.0,5.0,COD,2023-03-31,2023-04-13,Cancelled,3.0,Yes
1023,1024,1934,Raj,a@gmail.com,8.888889e+09,Mumbai,MP,India,523,Laptop,Accessories,2000.0,4.0,15.0,COD,2023-08-31,2023-05-21,Cancelled,3.0,Yes
1081,1082,1413,Raj,a@gmail.com,8.888889e+09,Bhopal,MP,India,516,Bag,Accessories,3000.0,1.0,15.0,UPI,2023-09-01,2023-03-15,Delivered,4.0,Yes
1135,1136,1839,Sara,a@gmail.com,1.000000e+10,Bhopal,DL,USA,665,Shoes,Accessories,4000.0,1.0,5.0,Card,2023-07-25,2023-05-27,Pending,5.0,No
1157,1158,1290,Raj,c@gmail.com,1.000000e+10,Bhopal,DL,UK,621,Bag,Electronics,1000.0,2.0,10.0,COD,2023-11-10,2023-04-29,Delivered,2.0,Yes
1195,1196,1451,John,c@gmail.com,1.000000e+10,Delhi,MP,UK,687,Laptop,Accessories,1000.0,2.0,5.0,UPI,2023-05-15,2023-04-26,Delivered,3.0,No
1215,1216,1382,Amit,b@gmail.com,1.000000e+10,Mumbai,MH,India,683,Shoes,Fashion,2000.0,4.0,10.0,UPI,2023-08-10,2023-03-17,Cancelled,4.0,Yes
1231,1232,1729,Riya,a@gmail.com,8.888889e+09,Delhi,DL,India,566,Laptop,Accessories,2000.0,3.0,0.0,Card,2023-02-13,2023-07-31,Pending,1.0,Yes
1311,1312,1244,John,b@gmail.com,1.000000e+10,Mumbai,MP,India,670,Watch,Electronics,4000.0,4.0,15.0,UPI,2023-07-16,2023-04-19,Delivered,5.0,Yes
1320,1321,1097,John,b@gmail.com,8.888889e+09,Indore,DL,UK,544,Phone,Accessories,3000.0,2.0,5.0,UPI,2023-01-10,2023-11-15,Cancelled,4.0,Yes
1325,1326,1993,John,c@gmail.com,1.000000e+10,Mumbai,MH,UK,642,Phone,Accessories,4000.0,4.0,0.0,Card,2023-02-08,2023-11-22,Pending,3.0,No
1337,1338,1919,Sara,b@gmail.com,8.888889e+09,Bhopal,MH,UK,686,Bag,Accessories,3000.0,4.0,5.0,UPI,2023-11-02,2023-10-25,Delivered,4.0,Yes
1342,1343,1634,Riya,a@gmail.com,1.000000e+10,Delhi,DL,UK,591,Phone,Fashion,2000.0,1.0,5.0,COD,2023-07-18,2023-01-17,Pending,1.0,Yes
1385,1386,1391,Amit,a@gmail.com,8.888889e+09,Mumbai,MH,UK,591,Laptop,Accessories,4000.0,2.0,15.0,UPI,2023-03-16,2023-10-28,Cancelled,3.0,No
1421,1422,1590,Riya,a@gmail.com,8.888889e+09,Mumbai,MH,India,620,Watch,Electronics,4000.0,3.0,15.0,COD,2023-07-20,2023-03-26,Cancelled,5.0,No
1606,1607,1598,John,b@gmail.com,7.777778e+09,Indore,MH,India,604,Phone,Accessories,2000.0,4.0,0.0,Card,2023-06-02,2023-06-23,Pending,5.0,Yes
1626,1627,1288,Raj,c@gmail.com,7.777778e+09,Bhopal,DL,India,560,Phone,Fashion,3000.0,3.0,5.0,Card,2023-08-04,2023-02-21,Cancelled,3.0,No
1645,1646,1697,Raj,c@gmail.com,8.888889e+09,Mumbai,MP,UK,683,Shoes,Accessories,2000.0,1.0,10.0,UPI,2023-08-21,2023-06-10,Pending,5.0,No
1652,1653,1466,Amit,b@gmail.com,7.777778e+09,Indore,MP,UK,522,Laptop,Fashion,2000.0,1.0,0.0,UPI,2023-01-25,2023-02-11,Delivered,1.0,Yes
1673,1674,1036,John,c@gmail.com,8.888889e+09,Mumbai,MH,USA,542,Watch,Accessories,1000.0,2.0,5.0,COD,2023-03-19,2023-08-25,Delivered,4.0,No
1728,1729,1140,Sara,b@gmail.com,1.000000e+10,Mumbai,MH,UK,654,Watch,Fashion,2000.0,1.0,10.0,Card,2023-12-25,2023-03-11,Pending,4.0,Yes
1927,1928,1945,Raj,c@gmail.com,8.888889e+09,Bhopal,DL,UK,675,Phone,Electronics,2000.0,2.0,0.0,COD,2023-05-10,2023-12-07,Delivered,3.0,No
1937,1938,1106,John,c@gmail.com,1.000000e+10,Mumbai,MH,USA,533,Phone,Fashion,2000.0,4.0,15.0,UPI,2023-12-05,2023-01-08,Cancelled,4.0,Yes
1967,1968,1645,John,a@gmail.com,7.777778e+09,Bhopal,MH,India,624,Laptop,Electronics,1000.0,1.0,5.0,COD,2023-01-28,2023-12-27,Delivered,1.0,No
1984,1985,1381,John,c@gmail.com,8.888889e+09,Indore,MP,UK,639,Shoes,Electronics,4000.0,2.0,0.0,Card,2023-11-29,2023-02-13,Delivered,3.0,No