In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("file1.csv")

In [4]:
df.head(0)

Empty DataFrame
Columns: [Order_ID, Customer_ID, Customer_Name, Email, Phone, Age, Gender, City, State, Country, ZIP_Code, Product_Category, Product_Name, SKU, Quantity, Unit_Price, Discount_%, Total_Amount, Order_Date, Ship_Date, Delivery_Date, Payment_Method, Order_Status, Sales_Rep, Department, Rating, Return_Reason, Is_Repeat_Customer, Loyalty_Points, Notes]
Index: []

[0 rows x 30 columns]

In [9]:
print(df)

       Order_ID Customer_ID   Customer_Name                         Email  \
0     ORD-10031   CUST-4688  Priya Williams  priya.williams17@hotmail.com
1     ORD-10109   CUST-4243    David Chopra    david.chopra64@outlook.com
2     ORD-10136   CUST-2721    Amanda Jones      amanda.jones37@yahoo.com
3     ORD-10088   CUST-1264  Aarav Williams    aarav.williams52@yahoo.com
4     ORD-10918   CUST-3103     Maria Brown      maria.brown42@company.in
...         ...         ...             ...                           ...
1025  ORD-10087   CUST-1645      Juan Smith        juan.smith41@yahoo.com
1026  ORD-10330   CUST-2277     Maria Joshi       maria.joshi92@yahoo.com
1027  ORD-10466   CUST-4073     Rahul Davis     rahul.davis13@outlook.com
1028  ORD-10121   CUST-1318    Rohit Miller    rohit.miller34@hotmail.com
1029  ORD-10860   CUST-4266     Maria Brown       maria.brown36@gmail.com

               Phone   Age  Gender          City         State  Country  ...  \
0     +91-7881351238  21.0    male    Birmingham  Pennsylvania      USA  ...
1     +91-7076317824  49.0       F       Chicago   West Bengal    India  ...
2     +91-8882985094  19.0    Male       Chennai  Pennsylvania       UK  ...
3     +91-9707107352  21.0  Female      New York           NaN    India  ...
4     +91-8228346162   NaN       M   Los Angeles     Telangana  Germany  ...
...              ...   ...     ...           ...           ...      ...  ...
1025  +91-9301778419  24.0    male       Chicago      Scotland      USA  ...
1026  +91-7042181691  64.0       F     Hyderabad   West Bengal       UK  ...
1027  +91-9944934815   NaN    male  Philadelphia  Pennsylvania      USA  ...
1028  +91-9448819206  51.0       F     Ahmedabad   Maharashtra   France  ...
1029  +91-7080234307   NaN    Male       Chicago       Gujarat       UK  ...

      Delivery_Date    Payment_Method Order_Status      Sales_Rep  \
0        2023-07-30        Debit Card     Returned  Pradeep Kumar
1        2024-02-21               COD     Returned   Sunita Singh
2        2023-07-22               UPI      Pending     Amit Verma
3        2024-07-24        debit card    Delivered    Alice Brown
4        2023-04-27               UPI      Pending    Neha Sharma
...             ...               ...          ...            ...
1025     2023-10-20  Cash on Delivery      Shipped    Alice Brown
1026     2024-02-13               NaN    Cancelled    Alice Brown
1027     2024-03-06               UPI    Cancelled      Dan Smith
1028     2024-01-22               UPI     Returned    Bob Johnson
1029     2023-01-20            Wallet    Delivered      Dan Smith

         Department  Rating     Return_Reason  Is_Repeat_Customer  \
0               NaN     1.0  Not as described                True
1     International     1.0               NaN                 NaN
2         East Zone     NaN        Wrong item               False
3        North Zone     NaN         Defective                 Yes
4        North Zone     4.0  Not as described                 Yes
...             ...     ...               ...                 ...
1025     South Zone     3.0        Wrong item               False
1026     North Zone     3.0         Defective                  No
1027     South Zone     2.0      Changed mind                  No
1028      East Zone     2.0               NaN                 Yes
1029      West Zone     2.0        Wrong item                 NaN

     Loyalty_Points                    Notes
0             211.0          Urgent delivery
1             444.0  Express shipping needed
2               NaN                      NaN
3               NaN                      NaN
4            3114.0                      NaN
...             ...                      ...
1025         3246.0                      NaN
1026         1281.0                Gift wrap
1027         2545.0                      NaN
1028         4949.0         Handle with care
1029         1075.0          Urgent delivery

[1030 rows x 30 columns]

In [8]:
df1=df.dropna()
# df1.head(0)
print(df1)

       Order_ID Customer_ID      Customer_Name  \
17    ORD-10664   CUST-4055  Isabella Williams
85    ORD-10086   CUST-2877       Pedro Sharma
116   ORD-10757   CUST-4118       Ana Williams
132   ORD-10628   CUST-1648     Divya Williams
141   ORD-10869   CUST-3843        Rohit Smith
168   ORD-10478   CUST-2499      Jessica Mehta
253   ORD-10440   CUST-1304      Jessica Davis
254   ORD-10346   CUST-4047       Rahul Garcia
272   ORD-10359   CUST-4576        Emily Smith
331   ORD-10518   CUST-4979      Sarah Johnson
494   ORD-10636   CUST-4117       Rahul Garcia
530   ORD-10124   CUST-4518       Rahul Garcia
541   ORD-10099   CUST-1669        Pedro Patel
565   ORD-10271   CUST-3305      Vikram Sharma
572   ORD-10578   CUST-3043        Sofia Gupta
590   ORD-10263   CUST-1812       Vikram Verma
598   ORD-10124   CUST-4518       Rahul Garcia
624   ORD-10287   CUST-2548        Luis Wilson
739   ORD-10751   CUST-1439       Pooja Wilson
815   ORD-10384   CUST-4303       Pooja Wilson
819   ORD-10472   CUST-3214         Ana Sharma
866   ORD-10883   CUST-4964        Divya Brown
869   ORD-10768   CUST-3119        Pedro Singh
880   ORD-10727   CUST-4735      James Johnson
922   ORD-10791   CUST-4954        Karan Verma
978   ORD-10166   CUST-4365        Karan Verma
1015  ORD-10805   CUST-2069        James Gupta

                                Email           Phone   Age  Gender  \
17    isabella.williams72@hotmail.com  +91-9349083473  49.0       M
85         pedro.sharma19@outlook.com  +91-7399546384  44.0    male
116          ana.williams68@yahoo.com  +91-8230488880  24.0   Other
132      divya.williams19@hotmail.com  +91-9666362215  43.0  Female
141           rohit.smith63@yahoo.com  +91-7823285853  31.0    Male
168         jessica.mehta12@yahoo.com  +91-8948526738  41.0       M
253          jessica.davis8@gmail.com  +91-9855395883  36.0  FEMALE
254          rahul.garcia75@gmail.com  +91-8510223792  47.0       F
272         emily.smith63@outlook.com  +91-9269449477  59.0       M
331          sarah.johnson1@gmail.com  +91-9455173689  37.0   Other
494        rahul.garcia98@hotmail.com  +91-7710850586  54.0  FEMALE
530         rahul.garcia62@company.in  +91-8637398296  62.0  Female
541           pedro.patel31@gmail.com  +91-9551397793  58.0   Other
565       vikram.sharma81@hotmail.com  +91-7040356227  23.0       M
572           sofia.gupta24@yahoo.com  +91-7033992093  45.0    male
590          vikram.verma85@gmail.com  +91-7695073055  35.0       M
598         rahul.garcia62@company.in  +91-8637398296  62.0  Female
624         luis.wilson46@outlook.com  +91-9802563740  26.0  FEMALE
739        pooja.wilson79@hotmail.com  +91-7363167072  30.0   Other
815           pooja.wilson5@yahoo.com  +91-7469628454  30.0    male
819            ana.sharma64@gmail.com  +91-8739825492  62.0   Other
866            divya.brown8@yahoo.com  +91-8998594189  26.0       F
869           pedro.singh49@yahoo.com  +91-7763106903  59.0    male
880       james.johnson15@outlook.com  +91-8936184007  38.0  FEMALE
922         karan.verma45@outlook.com  +91-8416278490  23.0   Other
978           karan.verma90@yahoo.com  +91-7776569551  41.0    Male
1015        james.gupta13@outlook.com  +91-8200264359  64.0  Female

              City         State  Country  ...  Delivery_Date  \
17    Philadelphia       England      USA  ...     2023-03-22
85      Birmingham       Gujarat   France  ...     2023-11-26
116        Phoenix     Karnataka    India  ...     2024-03-03
132        Chennai    California      USA  ...     2022-09-29
141          Delhi    Tamil Nadu      USA  ...     2024-06-05
168        Chennai    California  Germany  ...     2022-04-15
253          Leeds    Tamil Nadu       UK  ...     2023-12-01
254          Delhi  Pennsylvania  Germany  ...     2023-12-19
272    San Antonio     Telangana       UK  ...     2023-02-23
331         Mumbai     Karnataka    India  ...     2024-08-04
494    Los Angeles   West Bengal      USA  ...     2022-12-20
530     Birmingham         Texas    India  ...     2022-09-30
541           Pune     Telangana    India  ...     2023-06-02
565        Chennai       England       UK  ...     2022-07-30
572          Delhi      New York    India  ...     2022-09-10
590        Chennai    California    India  ...     2023-04-18
598     Birmingham         Texas    India  ...     2022-09-30
624   Philadelphia   Maharashtra   France  ...     2022-11-20
739        Chennai       England      USA  ...     2022-03-02
815    Los Angeles         Texas      USA  ...     2023-06-28
819      Ahmedabad      Illinois       UK  ...     2024-10-22
866    Los Angeles    California  Germany  ...     2023-12-23
869          Leeds   West Bengal    India  ...     2023-02-12
880         London   West Bengal       UK  ...     2024-11-12
922     Birmingham     Telangana       UK  ...     2023-11-11
978       New York    Tamil Nadu  Germany  ...     2023-06-22
1015    Manchester   Maharashtra   France  ...     2022-05-10

        Payment_Method Order_Status       Sales_Rep     Department  Rating  \
17         Credit Card     Returned   Pradeep Kumar     South Zone     1.0
85                 COD      Shipped     Bob Johnson     North Zone     1.0
116         Debit Card   Processing     Bob Johnson      West Zone     1.0
132         Debit Card   Processing       Raj Patel      East Zone     4.0
141                EMI      Pending       Raj Patel      West Zone     5.0
168         Debit Card      Pending       Dan Smith     North Zone     1.0
253        CREDIT CARD      Pending   Pradeep Kumar      West Zone     2.0
254        Credit Card      Shipped     Bob Johnson         Online     5.0
272                EMI     Returned     Alice Brown  International     1.0
331   Cash on Delivery      Pending     Neha Sharma  International     3.0
494                UPI      Pending  Carol Williams     South Zone     3.0
530         debit card   Processing    Sunita Singh     North Zone     3.0
541   Cash on Delivery   Processing      Amit Verma      West Zone     4.0
565        credit card    Cancelled       Raj Patel     South Zone     1.0
572   Cash on Delivery   Processing     Alice Brown      East Zone     3.0
590        Credit Card    Cancelled     Alice Brown     North Zone     2.0
598         debit card   Processing    Sunita Singh     North Zone     3.0
624        Net Banking      Shipped      Amit Verma  International     2.0
739   Cash on Delivery      Pending  Carol Williams         Online     1.0
815                EMI      Pending       Raj Patel      West Zone     1.0
819        Credit Card      Shipped     Alice Brown      East Zone     5.0
866   Cash on Delivery    Cancelled   Pradeep Kumar     South Zone     1.0
869        Net Banking      Shipped  Carol Williams      East Zone     5.0
880        Credit Card      Pending       Dan Smith  International     5.0
922   Cash on Delivery     Returned     Bob Johnson  International     5.0
978         Debit Card      Shipped  Carol Williams  International     5.0
1015               UPI   Processing      Amit Verma     North Zone     4.0

         Return_Reason  Is_Repeat_Customer Loyalty_Points  \
17           Defective                True         1343.0
85           Defective                 Yes         1070.0
116   Not as described                 Yes         1789.0
132          Defective               False          867.0
141          Defective               False         1505.0
168       Changed mind                 Yes         2599.0
253          Defective                True         2684.0
254         Wrong item                True         1731.0
272         Wrong item                True         4573.0
331   Not as described                 Yes         4932.0
494       Changed mind                  No         2180.0
530          Defective                  No         4257.0
541          Defective               False         1755.0
565          Defective                  No         4453.0
572       Changed mind                  No         1398.0
590   Not as described               False         2177.0
598          Defective                  No         4257.0
624         Wrong item                True         4881.0
739   Not as described                 Yes         2783.0
815          Defective                  No         1548.0
819   Not as described                True         2998.0
866       Changed mind                True         3604.0
869         Wrong item                  No         2084.0
880       Changed mind                 Yes         3571.0
922   Not as described                 Yes          985.0
978   Not as described               False         2826.0
1015        Wrong item               False         4437.0

                        Notes
17           Handle with care
85    Express shipping needed
116          Handle with care
132                 Gift wrap
141           Urgent delivery
168          Handle with care
253           Urgent delivery
254                 Gift wrap
272                 Gift wrap
331           Urgent delivery
494                 Gift wrap
530          Handle with care
541   Express shipping needed
565                 Gift wrap
572                 Gift wrap
590                 Gift wrap
598          Handle with care
624                 Gift wrap
739                 Gift wrap
815   Express shipping needed
819          Handle with care
866           Urgent delivery
869          Handle with care
880                 Gift wrap
922                 Gift wrap
978          Handle with care
1015  Express shipping needed

[27 rows x 30 columns]

In [10]:
df2=df.fillna("data")

In [11]:
df2

,Order_ID,Customer_ID,Customer_Name,Email,Phone,Age,Gender,City,State,Country,...,Delivery_Date,Payment_Method,Order_Status,Sales_Rep,Department,Rating,Return_Reason,Is_Repeat_Customer,Loyalty_Points,Notes
0,ORD-10031,CUST-4688,Priya Williams,priya.williams17@hotmail.com,+91-7881351238,21.0,male,Birmingham,Pennsylvania,USA,...,2023-07-30,Debit Card,Returned,Pradeep Kumar,data,1.0,Not as described,True,211.0,Urgent delivery
1,ORD-10109,CUST-4243,David Chopra,david.chopra64@outlook.com,+91-7076317824,49.0,F,Chicago,West Bengal,India,...,2024-02-21,COD,Returned,Sunita Singh,International,1.0,data,data,444.0,Express shipping needed
2,ORD-10136,CUST-2721,Amanda Jones,amanda.jones37@yahoo.com,+91-8882985094,19.0,Male,Chennai,Pennsylvania,UK,...,2023-07-22,UPI,Pending,Amit Verma,East Zone,data,Wrong item,False,data,data
3,ORD-10088,CUST-1264,Aarav Williams,aarav.williams52@yahoo.com,+91-9707107352,21.0,Female,New York,data,India,...,2024-07-24,debit card,Delivered,Alice Brown,North Zone,data,Defective,Yes,data,data
4,ORD-10918,CUST-3103,Maria Brown,maria.brown42@company.in,+91-8228346162,data,M,Los Angeles,Telangana,Germany,...,2023-04-27,UPI,Pending,Neha Sharma,North Zone,4.0,Not as described,Yes,3114.0,data
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1025,ORD-10087,CUST-1645,Juan Smith,juan.smith41@yahoo.com,+91-9301778419,24.0,male,Chicago,Scotland,USA,...,2023-10-20,Cash on Delivery,Shipped,Alice Brown,South Zone,3.0,Wrong item,False,3246.0,data
1026,ORD-10330,CUST-2277,Maria Joshi,maria.joshi92@yahoo.com,+91-7042181691,64.0,F,Hyderabad,West Bengal,UK,...,2024-02-13,data,Cancelled,Alice Brown,North Zone,3.0,Defective,No,1281.0,Gift wrap
1027,ORD-10466,CUST-4073,Rahul Davis,rahul.davis13@outlook.com,+91-9944934815,data,male,Philadelphia,Pennsylvania,USA,...,2024-03-06,UPI,Cancelled,Dan Smith,South Zone,2.0,Changed mind,No,2545.0,data
1028,ORD-10121,CUST-1318,Rohit Miller,rohit.miller34@hotmail.com,+91-9448819206,51.0,F,Ahmedabad,Maharashtra,France,...,2024-01-22,UPI,Returned,Bob Johnson,East Zone,2.0,data,Yes,4949.0,Handle with care
1029,ORD-10860,CUST-4266,Maria Brown,maria.brown36@gmail.com,+91-7080234307,data,Male,Chicago,Gujarat,UK,...,2023-01-20,Wallet,Delivered,Dan Smith,West Zone,2.0,Wrong item,data,1075.0,Urgent delivery

In [12]:
df2.head(0)

Empty DataFrame
Columns: [Order_ID, Customer_ID, Customer_Name, Email, Phone, Age, Gender, City, State, Country, ZIP_Code, Product_Category, Product_Name, SKU, Quantity, Unit_Price, Discount_%, Total_Amount, Order_Date, Ship_Date, Delivery_Date, Payment_Method, Order_Status, Sales_Rep, Department, Rating, Return_Reason, Is_Repeat_Customer, Loyalty_Points, Notes]
Index: []

[0 rows x 30 columns]